### ISSUE TITLE
Static constants for the CrashReporter are not found

### ISSUE THREAD

**Issue by ingrid-uk** [zeoflow/flow-kit#23]
data location `com.zeoflow.crash.reporter.utils`

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/zeoflow/flow-kit/releases) of the library.

We also happily accept [pull requests](https://github.com/zeoflow/flow-kit/pulls).

**Comment by teogor** [comment]
It was due to the static type. The above PR should fix this error
